🔧 update cpp-linter configuration

diff --git a/.github/workflows/cpp-linter.yml b/.github/workflows/cpp-linter.yml
--- a/.github/workflows/cpp-linter.yml
+++ b/.github/workflows/cpp-linter.yml
@@ -1,44 +1,65 @@
 name: cpp-linter
 
 on:
-  pull_request:
   push:
     branches:
       - main
+  pull_request:
+  merge_group:
+  workflow_dispatch:
 
 concurrency:
   group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
   cancel-in-progress: true
 
-env:
-  CC: clang-14
-  CXX: clang++-14
-
 jobs:
-  cpp-linter:
-    runs-on: ubuntu-22.04
+  lint:
+    name: 🚨 Lint
+    runs-on: ubuntu-latest
+    env:
+      clang-version: 16
     steps:
       - uses: actions/checkout@v4
         with:
           submodules: recursive
-      - name: Install flint
-        run: sudo apt-get install libflint-dev
+      - name: Install clang-${{ env.clang-version }}
+        run: |
+          sudo apt-get update
+          wget https://apt.llvm.org/llvm.sh -O ${{ runner.temp }}/llvm_install.sh
+          chmod +x ${{ runner.temp }}/llvm_install.sh
+          if sudo ${{ runner.temp }}/llvm_install.sh ${{ env.clang-version }}; then
+            sudo apt-get install -y clang-format-${{ env.clang-version }} clang-tidy-${{ env.clang-version }} || exit 1
+          else
+            echo "Installation from script failed."
+            exit 1
+          fi
+          echo "CC=clang-${{ env.clang-version }}" >> $GITHUB_ENV
+          echo "CXX=clang++-${{ env.clang-version }}" >> $GITHUB_ENV
+
       - name: Generate compilation database
         run: |
-          cmake -S . -B build -DBINDINGS=ON -DBUILD_QECC_TESTS=ON
+          echo $CC
+          echo $CXX
+          $CC --version
+          $CXX --version
+          cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug
+
       - name: Run cpp-linter
+        uses: cpp-linter/cpp-linter-action@v2
         id: linter
         env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        run: |
-          pipx run cpp-linter \
-          --version=14 \
-          --style="" \
-          --tidy-checks="" \
-          --thread-comments=true \
-          --files-changed-only=true \
-          --ignore="build|flint2" \
-          --database=build
+          GITHUB_TOKEN: ${{ github.token }}
+        with:
+          style: ""
+          tidy-checks: ""
+          version: ${{ env.clang-version }}
+          ignore: "build|include/python|src/python"
+          thread-comments: ${{ github.event_name == 'pull_request' }}
+          step-summary: true
+          database: "build"
+          extra-args: -std=c++17
+          files-changed-only: true
+
       - name: Fail if linter found errors
         if: steps.linter.outputs.checks-failed > 0
         run: echo "Linter found errors" && exit 1
